In [2]:
import pandas as pd

Creación del Dataframe 
Incluye: Datos Duplicados -Valores Nulos -Diferentes Areas y ciudadades

In [7]:
import pandas as pd

# Dataset simulado más completo
data = {
    "nombre": ["Ana", "Luis", "Carlos", "Marta", "Pedro", "Sofia", "Andres", "Laura", "Ana", "Carlos"],
    "edad": [23, 35, 29, 40, None, 31, 28, 45, 23, 29],
    "ciudad": ["Bogotá", "Cali", "Medellín", "Bogotá", "Cali", "Bogotá", "Medellín", "Cali", "Bogotá", "Medellín"],
    "salario": [1750000, 1900000, 2100000, 22000000, 2300000, 2800000, 3250000, 21000000, 4200000, 5100000],
    "area": ["Ventas", "TI", "Ventas", "Gerencia", "TI", "Ventas", "TI", "Gerencia", "Ventas", "Ventas"]
}

df = pd.DataFrame(data)

df

   nombre  edad    ciudad   salario      area
0     Ana  23.0    Bogotá   1750000    Ventas
1    Luis  35.0      Cali   1900000        TI
2  Carlos  29.0  Medellín   2100000    Ventas
3   Marta  40.0    Bogotá  22000000  Gerencia
4   Pedro   NaN      Cali   2300000        TI
5   Sofia  31.0    Bogotá   2800000    Ventas
6  Andres  28.0  Medellín   3250000        TI
7   Laura  45.0      Cali  21000000  Gerencia
8     Ana  23.0    Bogotá   4200000    Ventas
9  Carlos  29.0  Medellín   5100000    Ventas

Exploración de datos 

head-Como se ven los datos
info -Tipos de datos
describe -Estadisticas
shape- Tamaña de Dataset

In [8]:
df.head()
df.info()
df.describe()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nombre   10 non-null     str
 1   edad     9 non-null      float64
 2   ciudad   10 non-null     str
 3   salario  10 non-null     int64
 4   area     10 non-null     str
dtypes: float64(1), int64(1), str(3)
memory usage: 532.0 bytes

(10, 5)

Limpieza de Datos
Se reemplaza el valor faltante con promedio, para no perder información

In [9]:
df.isnull().sum()

nombre     0
edad       1
ciudad     0
salario    0
area       0
dtype: int64

In [12]:
df["edad"] = df["edad"].fillna(df["edad"].mean())

Verificando la modificación

In [13]:
df.isnull().sum()

nombre     0
edad       0
ciudad     0
salario    0
area       0
dtype: int64

Eliminar Duplicados
False-No esta repetido
True -Es un duplicado

In [14]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

Conteo de duplicados donde el esperado es 0, Por lo tanto no requiere limpieza en este paso

In [15]:
df.duplicated().sum()

np.int64(0)

Transformación de Datos 
Se crea una nueva columna  "Salaeio Anual" a partir de salario mensual para un analisis

In [18]:

df["salario_anual"] = df["salario"] * 12

df

   nombre       edad    ciudad   salario      area  salario_anual grupo_edad
0     Ana  23.000000    Bogotá   1750000    Ventas       21000000      Joven
1    Luis  35.000000      Cali   1900000        TI       22800000     Adulto
2  Carlos  29.000000  Medellín   2100000    Ventas       25200000      Joven
3   Marta  40.000000    Bogotá  22000000  Gerencia      264000000     Adulto
4   Pedro  31.444444      Cali   2300000        TI       27600000     Adulto
5   Sofia  31.000000    Bogotá   2800000    Ventas       33600000     Adulto
6  Andres  28.000000  Medellín   3250000        TI       39000000      Joven
7   Laura  45.000000      Cali  21000000  Gerencia      252000000     Adulto
8     Ana  23.000000    Bogotá   4200000    Ventas       50400000      Joven
9  Carlos  29.000000  Medellín   5100000    Ventas       61200000      Joven

Clasificación por edad
Transformación de datos numericos en categorias

In [19]:

df["grupo_edad"] = df["edad"].apply(lambda x: "Joven" if x < 30 else "Adulto")

df

   nombre       edad    ciudad   salario      area  salario_anual grupo_edad
0     Ana  23.000000    Bogotá   1750000    Ventas       21000000      Joven
1    Luis  35.000000      Cali   1900000        TI       22800000     Adulto
2  Carlos  29.000000  Medellín   2100000    Ventas       25200000      Joven
3   Marta  40.000000    Bogotá  22000000  Gerencia      264000000     Adulto
4   Pedro  31.444444      Cali   2300000        TI       27600000     Adulto
5   Sofia  31.000000    Bogotá   2800000    Ventas       33600000     Adulto
6  Andres  28.000000  Medellín   3250000        TI       39000000      Joven
7   Laura  45.000000      Cali  21000000  Gerencia      252000000     Adulto
8     Ana  23.000000    Bogotá   4200000    Ventas       50400000      Joven
9  Carlos  29.000000  Medellín   5100000    Ventas       61200000      Joven

 Preguntas de análisis

1. ¿Cuál es el salario promedio por ciudad?
2. ¿Qué área tiene el salario promedio más alto?
3. ¿Qué porcentaje de personas gana más que el salario promedio?

In [22]:
# Salario promedio por ciudad
df.groupby("ciudad")["salario"].mean()

ciudad
Bogotá     7,687,500
Cali       8,400,000
Medellín   3,483,333
Name: salario, dtype: float64

Varia segun la ciudad, donde se observa que calí presenta el promedio mas alto, seguida de Bogotá y Medellin el promedi mas bajo

## Pregunta 2
¿Cuál es el salario promedio por área?

In [23]:
df.groupby("area")["salario"].mean()

area
Gerencia   21,500,000
TI          2,483,333
Ventas      3,190,000
Name: salario, dtype: float64

Gerencia presenta los salario más altos, mientras que TI y ventas son los mas bajos

## Pregunta 3
¿Qué porcentaje de personas gana más que el salario promedio?

In [24]:
promedio = df["salario"].mean()
promedio

np.float64(6640000.0)

In [25]:
mayores_promedio = df[df["salario"] > promedio]

mayores_promedio

  nombre  edad  ciudad   salario      area  salario_anual grupo_edad
3  Marta    40  Bogotá  22000000  Gerencia      264000000     Adulto
7  Laura    45    Cali  21000000  Gerencia      252000000     Adulto

In [26]:

porcentaje = (len(mayores_promedio) / len(df)) * 100

porcentaje

20.0

## Conclusiones

En este taller se realizó un análisis de datos utilizando Pandas, comenzando por la exploración y limpieza del dataset. Se identificaron valores nulos en la columna de edad, los cuales fueron reemplazados por el promedio para no perder información. También se revisaron los datos duplicados, pero en este caso no fue necesario eliminarlos.

Luego, se crearon nuevas columnas como el salario anual y la clasificación por grupo de edad, lo que ayudó a entender mejor la información y facilitar el análisis.

A través de los filtros y las agrupaciones, se pudieron observar diferencias importantes. Por ejemplo, el salario promedio cambia dependiendo de la ciudad y del área de trabajo, lo que muestra que no todos tienen las mismas condiciones. Además, se identificó que solo una parte de las personas gana por encima del promedio, lo que indica que los ingresos no están distribuidos de manera equitativa.

En general, este ejercicio permitió entender cómo organizar, limpiar y analizar datos para obtener información útil que puede servir para la toma de decisiones.